ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'RBAC_ROLE_ASSIGNED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'RBAC_ROLE_REMOVED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'RBAC_PERMISSION_GRANTED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'RBAC_PERMISSION_REVOKED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'RBAC_SCOPE_CHANGED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'RBAC_PROJECT_ACCESS_GRANTED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'RBAC_PROJECT_ACCESS_REMOVED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'RBAC_USER_STATUS_CHANGED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'RBAC_ROLE_MAPPING_UPDATED';

ALTER TABLE "audit_logs"
  ADD COLUMN IF NOT EXISTS "target_user_snapshot" JSONB,
  ADD COLUMN IF NOT EXISTS "role_snapshot" JSONB,
  ADD COLUMN IF NOT EXISTS "permission_snapshot" JSONB,
  ADD COLUMN IF NOT EXISTS "scope_snapshot" JSONB,
  ADD COLUMN IF NOT EXISTS "project_snapshot" JSONB,
  ADD COLUMN IF NOT EXISTS "metadata" JSONB;
