ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'USER_SIGNATURE_UPLOADED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'USER_SIGNATURE_REPLACED';
ALTER TYPE "audit_action" ADD VALUE IF NOT EXISTS 'USER_SIGNATURE_DELETED';

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "signature_file_name" VARCHAR(250),
  ADD COLUMN IF NOT EXISTS "signature_mime_type" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "signature_file_size" BIGINT,
  ADD COLUMN IF NOT EXISTS "signature_file_hash" CHAR(64),
  ADD COLUMN IF NOT EXISTS "signature_file_url" TEXT,
  ADD COLUMN IF NOT EXISTS "signature_uploaded_at" TIMESTAMP(6);
